#index:
#    path: /
#    controller: App\Controller\DefaultController::index

registro:
    path: /register
    controller: App\Controller\UserController::register 

bienvenida:
  path: /welcome-landing
  controller: App\Controller\UserController::bienvenida

login:
  path: /login
  controller: App\Controller\UserController::login
